
name: adja-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - ipykernel
python :
  - -m ipykernel install --user --name=python-env --display-name "adja-kernel"